name: Django Queryset ERD Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*" # Trigger on push of version tags (e.g., v1.0.0)
    paths:
    - django_queryset_erd/** # Trigger on changes to the package code
    - setup.cfg # Trigger on changes to the package metadata

  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths:
    - django_queryset_erd/** # Trigger on changes to the package code
    - setup.cfg # Trigger on changes to the package metadata

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]
        django-version: ["4.2", "5.0"]
    steps:
      - name: Get the Code
        uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Django==${{ matrix.django-version }}
          pip install -e .
          pip install pytest pytest-django
      - name: Run Tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest